---

- hosts: all
  become: true
  tasks:
   
  - name: install updates
    tags: updates
    package:
    
      update_cache: yes
    changed_when: false 

- hosts: file_servers
  become: true
  tasks:

  - name: copy files 
    tags: copy
    copy:
      src: copy_test.txt 
      dest: ~/copy_success1.txt
      owner: root
      group: root
      mode: 0700

- hosts: all
  become: true
  tasks:
  
  - name: add ssh key for  red
    tags: always
    authorized_key:
      user: red
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCuFoREe9nRB+Ij3exX98NC8XVpdxVfkj0L2Apsp3c0+etaop4ZcSK3dJ/oX3LU/GRlBGvX+MF0itjgaerXXueutTcgwep3fmdQi6vhMGnjJJ7X8xdLFsaBlkSYLdcEhDWiOHss6laSTViBBqnz8v0312Pqhp7oWRWDoOmC13M7z2YpbZI5+gB8RkoDWC2fx/3ia4YPBVuiXX5JLG4wtQmKq3lkDZUu9qHuaQkjX3KoonnIlYnBElY9wfHLimeEbKeJYec0N7m94CR1PloWAUr6zUytbsC287WDm12FJ5+4PBKy4xkT9fMmw3ekrYN7U9dOoTvWTzUsSDEh0ibIdLWongdatVnaY1FLcO4Ucoc0XHo+m9QFPFl4lJdvx1Nr/YrhBx+tZmmMfljJXwXR7mptFfzp87XIX/0vM5dWxG5T5NVdp8TYgIWGPTdT1sNQ2koSgpsK37zU9u3C9HhFN7RuFa+tw1m5nZk2LP3PFQPPdyAgcjuxvPo2+EiRvcwVOHE= root@ansible-interns"

- hosts: web_servers
  become: true
  tasks:

  - name: install unzip
    package: 
      name: unzip


  - name: install terraform
    tags: unarchive
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_arm64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: change email address for admin
    tags: change_email
    lineinfile:
      path: ~/bluetooth.txt
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    register: apache

  - name: restart apache2
    tags: apache2
    service:
      name: apache2
      state: restarted
    when: apache.changed
 
- hosts: file_servers
  become: true
  tasks:

  - name: to stop apache service
    tags: stop_service
    service:
      name: apache2
      state: stopped


