---

- hosts: all
  tasks:
 
  - name: remove apache and vim package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ vim_package }}"
      state: absent
      update_cache: yes 
      
      
